// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfEdit uIProj_nameEdit = this.UINovoProjetoWindow.UIProj_nameEdit;
            WpfEdit uIProj_nameEdit1 = this.UINovoArquivoWindow.UIProj_nameEdit;
            WpfListItem uIERDataModelEntityListItem = this.UIUFOPArchiDataWindow.UIItemTabList.UITCC2ViewModelItemVieTabPage.UIPART_DIAGRAMList.UIERDataModelEntityListItem;
            WpfList uIPART_DIAGRAMList = this.UIUFOPArchiDataWindow.UIItemTabList.UITCC2ViewModelItemVieTabPage.UIPART_DIAGRAMList;
            #endregion

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Type 'teste4' in 'proj_name' text box
            uIProj_nameEdit.Text = this.RecordedMethod1Params.UIProj_nameEditText;

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Element not available

            // Last mouse action was not recorded.

            // Type 'diagrama1' in 'proj_name' text box
            uIProj_nameEdit1.Text = this.RecordedMethod1Params.UIProj_nameEditText1;

            // Element not available

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Move 'ER.Data.Model.Entity' list item to 'PART_DIAGRAM' list box
            uIPART_DIAGRAMList.EnsureClickable(new Point(654, 261));
            Mouse.StartDragging(uIERDataModelEntityListItem, new Point(144, 52));
            Mouse.StopDragging(uIPART_DIAGRAMList, new Point(654, 261));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UINovoProjetoWindow UINovoProjetoWindow
        {
            get
            {
                if ((this.mUINovoProjetoWindow == null))
                {
                    this.mUINovoProjetoWindow = new UINovoProjetoWindow();
                }
                return this.mUINovoProjetoWindow;
            }
        }
        
        public UINovoArquivoWindow UINovoArquivoWindow
        {
            get
            {
                if ((this.mUINovoArquivoWindow == null))
                {
                    this.mUINovoArquivoWindow = new UINovoArquivoWindow();
                }
                return this.mUINovoArquivoWindow;
            }
        }
        
        public UIUFOPArchiDataWindow UIUFOPArchiDataWindow
        {
            get
            {
                if ((this.mUIUFOPArchiDataWindow == null))
                {
                    this.mUIUFOPArchiDataWindow = new UIUFOPArchiDataWindow();
                }
                return this.mUIUFOPArchiDataWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UINovoProjetoWindow mUINovoProjetoWindow;
        
        private UINovoArquivoWindow mUINovoArquivoWindow;
        
        private UIUFOPArchiDataWindow mUIUFOPArchiDataWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'teste4' in 'proj_name' text box
        /// </summary>
        public string UIProj_nameEditText = "teste4";
        
        /// <summary>
        /// Type 'diagrama1' in 'proj_name' text box
        /// </summary>
        public string UIProj_nameEditText1 = "diagrama1";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINovoProjetoWindow : WpfWindow
    {
        
        public UINovoProjetoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Novo Projeto";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Novo Projeto");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIProj_nameEdit
        {
            get
            {
                if ((this.mUIProj_nameEdit == null))
                {
                    this.mUIProj_nameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIProj_nameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "proj_name";
                    this.mUIProj_nameEdit.WindowTitles.Add("Novo Projeto");
                    #endregion
                }
                return this.mUIProj_nameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIProj_nameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINovoArquivoWindow : WpfWindow
    {
        
        public UINovoArquivoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Novo Arquivo";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Novo Arquivo");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIProj_nameEdit
        {
            get
            {
                if ((this.mUIProj_nameEdit == null))
                {
                    this.mUIProj_nameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIProj_nameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "proj_name";
                    this.mUIProj_nameEdit.WindowTitles.Add("Novo Arquivo");
                    #endregion
                }
                return this.mUIProj_nameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIProj_nameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUFOPArchiDataWindow : WpfWindow
    {
        
        public UIUFOPArchiDataWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "UFOP ArchiData";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("UFOP ArchiData");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTabList : WpfTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("UFOP ArchiData");
            #endregion
        }
        
        #region Properties
        public UITCC2ViewModelItemVieTabPage UITCC2ViewModelItemVieTabPage
        {
            get
            {
                if ((this.mUITCC2ViewModelItemVieTabPage == null))
                {
                    this.mUITCC2ViewModelItemVieTabPage = new UITCC2ViewModelItemVieTabPage(this);
                }
                return this.mUITCC2ViewModelItemVieTabPage;
            }
        }
        #endregion
        
        #region Fields
        private UITCC2ViewModelItemVieTabPage mUITCC2ViewModelItemVieTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITCC2ViewModelItemVieTabPage : WpfTabPage
    {
        
        public UITCC2ViewModelItemVieTabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "TCC2.ViewModel.ItemViewModel";
            this.WindowTitles.Add("UFOP ArchiData");
            #endregion
        }
        
        #region Properties
        public UIPART_DIAGRAMList UIPART_DIAGRAMList
        {
            get
            {
                if ((this.mUIPART_DIAGRAMList == null))
                {
                    this.mUIPART_DIAGRAMList = new UIPART_DIAGRAMList(this);
                }
                return this.mUIPART_DIAGRAMList;
            }
        }
        #endregion
        
        #region Fields
        private UIPART_DIAGRAMList mUIPART_DIAGRAMList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPART_DIAGRAMList : WpfList
    {
        
        public UIPART_DIAGRAMList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "PART_DIAGRAM";
            this.WindowTitles.Add("UFOP ArchiData");
            #endregion
        }
        
        #region Properties
        public WpfListItem UIERDataModelEntityListItem
        {
            get
            {
                if ((this.mUIERDataModelEntityListItem == null))
                {
                    this.mUIERDataModelEntityListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIERDataModelEntityListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "ER.Data.Model.Entity";
                    this.mUIERDataModelEntityListItem.WindowTitles.Add("UFOP ArchiData");
                    #endregion
                }
                return this.mUIERDataModelEntityListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUIERDataModelEntityListItem;
        #endregion
    }
}
